/*
 * GANSU: GPU Accelerated Numerical Simulation Utility
 *
 * Copyright (c) 2025-2026, Hiroshima University and Fujitsu Limited
 * All rights reserved.
 *
 * This software is licensed under the BSD 3-Clause License.
 * You may obtain a copy of the license in the LICENSE file
 * located in the root directory of this source tree or at:
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * @file test_validation.cu
 * @brief Validation tests comparing GANSU results against PySCF reference values.
 *
 * Reference values generated by script/validate_with_pyscf.py
 * PySCF settings: conv_tol=1e-12, cart=True for cc-pVDZ
 */

#include <gtest/gtest.h>
#include "builder.hpp"
#include "parameter_manager.hpp"
#include <iomanip>
#include <sstream>

using namespace gansu;

// ============================================================
//  PySCF reference values
// ============================================================

// RHF / STO-3G
constexpr real_t REF_H2_RHF_STO3G = -1.1175058842;
constexpr real_t REF_H2O_RHF_STO3G = -74.9659011616;
constexpr real_t REF_NH3_RHF_STO3G = -55.4554193875;
constexpr real_t REF_CH4_RHF_STO3G = -39.7268629038;
constexpr real_t REF_N2_RHF_STO3G = -107.5006541881;
constexpr real_t REF_HF_RHF_STO3G = -98.5728469737;

// RHF / cc-pVDZ (Cartesian)
constexpr real_t REF_H2O_RHF_ccpVDZ = -76.0234907752;

// UHF / STO-3G
constexpr real_t REF_O2_UHF_STO3G = -147.6364161566; // PySCF stability-optimized

// ROHF / STO-3G
constexpr real_t REF_O2_ROHF_STO3G = -147.6324148786;

// Post-HF / H2O / STO-3G
constexpr real_t REF_H2O_MP2_STO3G_corr = -0.0389637139;
constexpr real_t REF_H2O_CCSD_STO3G_corr = -0.0543962594;
constexpr real_t REF_H2O_CCSDT_STO3G_total = -75.0203643861;
constexpr real_t REF_H2O_FCI_STO3G_corr = -0.0545225877;

// RHF / cc-pVDZ (Cartesian) - additional molecules with d-functions
constexpr real_t REF_NH3_RHF_ccpVDZ = -56.1943219246;
constexpr real_t REF_CH4_RHF_ccpVDZ = -40.1985958587;

// Post-HF / H2O / cc-pVDZ (Cartesian)
constexpr real_t REF_H2O_MP2_ccpVDZ_corr = -0.2102563512;
constexpr real_t REF_H2O_CCSD_ccpVDZ_corr = -0.2192016272;
constexpr real_t REF_H2O_CCSDT_ccpVDZ_total = -76.2461303362;

// RHF / cc-pVTZ (Cartesian) - f-functions
constexpr real_t REF_H2O_RHF_ccpVTZ = -76.0531393100;

// Post-HF / H2O / cc-pVTZ (Cartesian)
constexpr real_t REF_H2O_MP2_ccpVTZ_corr = -0.2816708958;
constexpr real_t REF_H2O_CCSD_ccpVTZ_corr = -0.2870700626;
constexpr real_t REF_H2O_CCSDT_ccpVTZ_total = -76.3484466073;

// Post-HF / NH3 / cc-pVDZ (Cartesian)
constexpr real_t REF_NH3_CCSD_ccpVDZ_corr = -0.2097206001;
constexpr real_t REF_NH3_CCSDT_ccpVDZ_total = -56.4082625771;

// Post-HF / HF / cc-pVDZ (Cartesian)
constexpr real_t REF_HFmol_RHF_ccpVDZ = -100.0167900396;
constexpr real_t REF_HFmol_CCSD_ccpVDZ_corr = -0.2139496049;
constexpr real_t REF_HFmol_CCSDT_ccpVDZ_total = -100.2328803182;

// Post-HF / CH4 / cc-pVDZ (Cartesian)
constexpr real_t REF_CH4_CCSD_ccpVDZ_corr = -0.1895739578;
constexpr real_t REF_CH4_CCSDT_ccpVDZ_total = -40.3920273941;

// Tolerances
constexpr real_t TOL_POSTHF_TZ = 2e-5;  // Post-HF tolerance for cc-pVTZ (spin-orbital accumulates more FP error with 2x indices)
constexpr real_t TOL_HF = 1e-6;       // HF total energy tolerance
constexpr real_t TOL_POSTHF = 2e-6;   // Post-HF correlation energy tolerance (STO-3G)
constexpr real_t TOL_POSTHF_DZ = 5e-6; // Post-HF tolerance for cc-pVDZ (larger basis)
constexpr real_t TOL_RI = 2e-3;       // RI approximation tolerance (inherent fitting error)
constexpr real_t TOL_RI_AUTO = 5e-2;  // Auto-generated auxiliary basis tolerance (less accurate than optimized fitting basis)


// ============================================================
//  Helper: run GANSU calculation
// ============================================================

struct GansuResult {
    real_t hf_total_energy;
    real_t post_hf_energy;   // correlation energy (0 if no post-HF)
};

static GansuResult run_gansu(const std::string& xyz,
                              const std::string& basis,
                              const std::string& method,
                              const std::string& post_hf = "none",
                              int charge = 0,
                              int beta_to_alpha = 0,
                              const std::string& initial_guess = "core",
                              const std::string& eri_method = "stored",
                              const std::string& auxiliary_basis = "",
                              int ccsd_algorithm = 0)
{
    // Clear any sticky CUDA errors from previous tests
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = method;
    params["post_hf_method"] = post_hf;
    params["convergence_energy_threshold"] = "1e-10";
    params["charge"] = std::to_string(charge);
    params["beta_to_alpha"] = std::to_string(beta_to_alpha);
    params["initial_guess"] = initial_guess;
    params["eri_method"] = eri_method;
    if (!auxiliary_basis.empty()) {
        params["auxiliary_gbsfilename"] = auxiliary_basis;
    }
    if (ccsd_algorithm != 0) {
        params["ccsd_algorithm"] = std::to_string(ccsd_algorithm);
    }

    // Suppress GANSU's verbose output during solve
    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    // Restore stdout
    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy;
    if (post_hf != "none") {
        std::cout << "  post-HF corr = " << result.post_hf_energy
                  << "  total = " << result.hf_total_energy + result.post_hf_energy;
    }
    std::cout << std::endl;

    return result;
}

// Path prefix (test runs from test/build/)
static const std::string XYZ = "../xyz/";
static const std::string BASIS = "../basis/";
static const std::string AUX_BASIS = "../auxiliary_basis/";


// ============================================================
//  RHF / STO-3G
// ============================================================

TEST(ValidationRHF, H2_STO3G) {
    auto r = run_gansu(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, H2O_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, NH3_STO3G) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, CH4_STO3G) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, N2_STO3G) {
    auto r = run_gansu(XYZ + "N2.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "gwh");
    EXPECT_NEAR(r.hf_total_energy, REF_N2_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, HF_STO3G) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_HF_RHF_STO3G, TOL_HF);
}


// ============================================================
//  RHF / cc-pVDZ (with d-functions)
// ============================================================

TEST(ValidationRHF, H2O_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}


// ============================================================
//  ROHF / STO-3G
// ============================================================

TEST(ValidationROHF, O2_STO3G) {
    auto r = run_gansu(XYZ + "O2.xyz", BASIS + "sto-3g.gbs", "rohf",
                       "none", 0, 1, "core");
    EXPECT_NEAR(r.hf_total_energy, REF_O2_ROHF_STO3G, TOL_HF);
}


// ============================================================
//  UHF / STO-3G
// ============================================================

TEST(ValidationUHF, O2_STO3G) {
    auto r = run_gansu(XYZ + "O2.xyz", BASIS + "sto-3g.gbs", "uhf",
                       "none", 0, 1, "gwh");
    EXPECT_NEAR(r.hf_total_energy, REF_O2_UHF_STO3G, TOL_HF);
}


// ============================================================
//  Post-HF / H2O / STO-3G
// ============================================================

TEST(ValidationPostHF, H2O_MP2_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "mp2");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_CCSD_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "ccsd");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_CCSD_T_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "ccsd_t");
    real_t total = r.hf_total_energy + r.post_hf_energy;
    EXPECT_NEAR(total, REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_FCI_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "fci");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_FCI_STO3G_corr, TOL_POSTHF);
}


// ============================================================
//  Post-HF / H2O / cc-pVDZ (with d-functions)
// ============================================================

TEST(ValidationPostHF, H2O_MP2_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "mp2");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVDZ_corr, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_CCSD_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "ccsd");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}


TEST(ValidationPostHF, H2O_CCSD_T_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "ccsd_t");
    real_t total = r.hf_total_energy + r.post_hf_energy;
    std::cout << "  H2O CCSD(T)/cc-pVDZ total = " << std::fixed << std::setprecision(10)
              << total << std::endl;
    EXPECT_NEAR(total, REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}


// ============================================================
//  RHF / cc-pVDZ - additional molecules (d-functions)
// ============================================================

TEST(ValidationRHF, NH3_ccpVDZ) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_HF);
}

TEST(ValidationRHF, CH4_ccpVDZ) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_HF);
}


// ============================================================
//  RHF / cc-pVTZ (f-functions)
// ============================================================

TEST(ValidationRHF, H2O_ccpVTZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
}


// ============================================================
//  Post-HF / H2O / cc-pVTZ (f-functions)
// ============================================================

TEST(ValidationPostHF, H2O_MP2_ccpVTZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf", "mp2");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVTZ_corr, TOL_POSTHF);
}


// ============================================================
//  Direct-SCF (should match Stored ERI exactly)
// ============================================================

TEST(ValidationDirect, H2O_RHF_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationDirect, H2O_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}

TEST(ValidationDirect, NH3_RHF_STO3G) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_HF);
}


// ============================================================
//  RI approximation (looser tolerance due to fitting)
// ============================================================

TEST(ValidationRI, H2O_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI);
}

TEST(ValidationRI, NH3_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_RI);
}

TEST(ValidationRI, CH4_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_RI);
}

// ============================================================
//  RI approximation with auto-generated auxiliary basis
// ============================================================

TEST(ValidationRI_Auto, H2O_RHF_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_RI_AUTO);
}

TEST(ValidationRI_Auto, H2O_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI_AUTO);
}

TEST(ValidationRI_Auto, NH3_RHF_STO3G) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_RI_AUTO);
}

TEST(ValidationRI_Auto, CH4_RHF_STO3G) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_STO3G, TOL_RI_AUTO);
}

// ============================================================

TEST(ValidationRI, H2O_MP2_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "mp2", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVDZ_corr, TOL_RI);
}


// ============================================================
//  Benchmark: CCSD algorithm comparison (3 implementations)
//  Algorithm 0 = spatial-optimized (GPU DGEMM + sub-blocks)
//  Algorithm 1 = spatial-naive (no GPU, no sub-blocks)
//  Algorithm 2 = spin-orbital (legacy)
// ============================================================

// --- H2O / STO-3G / CCSD ---

TEST(BenchmarkCCSD, H2O_STO3G_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(BenchmarkCCSD, H2O_STO3G_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(BenchmarkCCSD, H2O_STO3G_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

// --- H2O / STO-3G / CCSD(T) ---

TEST(BenchmarkCCSD_T, H2O_STO3G_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(BenchmarkCCSD_T, H2O_STO3G_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(BenchmarkCCSD_T, H2O_STO3G_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

// --- H2O / cc-pVDZ / CCSD ---

TEST(BenchmarkCCSD, H2O_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD, H2O_ccpVDZ_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD, H2O_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

// --- H2O / cc-pVDZ / CCSD(T) ---

TEST(BenchmarkCCSD_T, H2O_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD_T, H2O_ccpVDZ_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD_T, H2O_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// ============================================================
//  Large-scale CCSD/CCSD(T) benchmarks
//  Spatial-optimized (algo=0) vs Spin-orbital (algo=2)
//  Naive (algo=1) excluded — too slow for large basis/molecules
// ============================================================

// --- H2O / cc-pVTZ (nocc=5, nvir=60) — key scaling test ---

TEST(LargeBenchmarkCCSD, H2O_ccpVTZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVTZ_corr, TOL_POSTHF_TZ);
}

TEST(LargeBenchmarkCCSD, H2O_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVTZ_corr, TOL_POSTHF_TZ);
}

TEST(LargeBenchmarkCCSD_T, H2O_ccpVTZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVTZ_total, TOL_POSTHF_TZ);
}

TEST(LargeBenchmarkCCSD_T, H2O_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVTZ_total, TOL_POSTHF_TZ);
}

// --- NH3 / cc-pVDZ (nocc=5, nvir=25) ---

TEST(LargeBenchmarkCCSD, NH3_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_NH3_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD, NH3_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_NH3_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, NH3_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_NH3_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, NH3_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_NH3_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// --- CH4 / cc-pVDZ (nocc=5, nvir=30) ---

TEST(LargeBenchmarkCCSD, CH4_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_CH4_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD, CH4_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_CH4_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, CH4_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_CH4_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, CH4_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_CH4_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// --- HF molecule / cc-pVDZ (nocc=5, nvir=15) ---

TEST(LargeBenchmarkCCSD, HFmol_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_HFmol_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_HFmol_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD, HFmol_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_HFmol_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_HFmol_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, HFmol_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_HFmol_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, HFmol_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_HFmol_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// ============================================================
//  PySCF comparison benchmarks: CCSD and CCSD(T) separately
//  Matches script/benchmark_ccsd_pyscf.py combinations
//  (H2O already covered in BenchmarkCCSD/BenchmarkCCSD_T above)
// ============================================================

// --- Formaldehyde / cc-pVDZ (nocc=8, nvir=32) --- medium molecule

TEST(BenchmarkCCSD, Formaldehyde_ccpVDZ_Spatial) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD, Formaldehyde_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
}

TEST(BenchmarkCCSD_T, Formaldehyde_ccpVDZ_Spatial) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD_T, Formaldehyde_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
}

// --- NH3 / cc-pVTZ (nocc=5, nvir=53) --- large basis scaling

TEST(BenchmarkCCSD, NH3_ccpVTZ_Spatial) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD, NH3_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
}

TEST(BenchmarkCCSD_T, NH3_ccpVTZ_Spatial) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD_T, NH3_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
}
